# Site settings
name: 全建誉
location: 广州
#company: 石家庄铁道大学
position: PHP|JAVA|GO|NODE
github: https://github.com/Yvesjava
#facebook: https://www.facebook.com/
#phone: 1863733XXXX
email: 164174421@qq.com

baseurl: ""

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

theme: jekyll-theme-slate1
